### ISSUE TITLE
Annotate runs into dictionary issue when iterating

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/annmas#18]
I tried running annmas in the docker container, and `annotate` produces the following:

```
[INFO 2021-02-08 15:01:18] annmas: annotate started
[INFO 2021-02-08 15:01:18] Running with 4 worker subprocess(es)
Traceback (most recent call last):
  File "/annmas/venv/bin/annmas", line 11, in <module>
    load_entry_point('annmas', 'console_scripts', 'annmas')()
  File "/annmas/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/annmas/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/annmas/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/annmas/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/annmas/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/annmas/src/annmas/annotate/command.py", line 91, in main
    m = build_default_model()
  File "/annmas/src/annmas/utils/model.py", line 272, in build_default_model
    full_model.bake()
  File "pomegranate/hmm.pyx", line 794, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/annmas/venv/lib/python3.8/site-packages/networkx/classes/reportviews.py", line 718, in <genexpr>
    for nbr, dd in nbrs.items()
RuntimeError: dictionary keys changed during iteration
double free or corruption (out)
Aborted (core dumped)
```

**Comment by jonn-smith** [comment]
This seems to be a library / python versioning issue.  I cannot yet replicate this outside the docker container.

**Comment by jonn-smith** [comment]
This is a problem in `python 3.8`, but works fine in `python 3.7.9`.

I have updated the docker image I'm using and it works now.  I will close this and add another issue to track the incompatibility with `python 3.8`.
