### ISSUE TITLE
ModuleNotFoundError: No module named 'ordered_set'

### ISSUE THREAD

**Issue by xuxia10** [broadinstitute/annmas#207]
Dear author,

Describe the bug

I input  longbow version

Traceback (most recent call last):
  File "/home/xuxia/miniconda3/envs/masseq2/bin/longbow", line 5, in <module>
    from longbow.__main__ import main_entry
  File "/home/xuxia/miniconda3/envs/masseq2/lib/python3.7/site-packages/longbow/__main__.py", line 36, in <module>
    exec(f"from .{p.name} import command as {p.name}")
  File "<string>", line 1, in <module>
  File "/home/xuxia/miniconda3/envs/masseq2/lib/python3.7/site-packages/longbow/correct/command.py", line 23, in <module>
    from ..utils import bam_utils, barcode_utils
  File "/home/xuxia/miniconda3/envs/masseq2/lib/python3.7/site-packages/longbow/utils/barcode_utils.py", line 11, in <module>
    from ordered_set import OrderedSet
ModuleNotFoundError: No module named 'ordered_set'

**Comment by hdm-23** [comment]
Have you tried installing 'ordered_set'?
'pip install ordered-set'
